// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform;
import 'package:flutter/material.dart' show TargetPlatform;

/// A class that exposes all available [FirebaseOptions] for different platforms.
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (defaultTargetPlatform == TargetPlatform.android) {
      return android;
    }
    if (defaultTargetPlatform == TargetPlatform.iOS) {
      return ios;
    }
    if (defaultTargetPlatform == TargetPlatform.windows) {
      return windows;
    }
    if (defaultTargetPlatform == TargetPlatform.linux) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for linux - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    if (defaultTargetPlatform == TargetPlatform.macOS) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for macos - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  /// Android Firebase configuration
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLqLjzLc3jH1e5kJ9pG8tM2nB7cD4fH5i',
    appId: '1:123456789012:android:abc123def456abc123def',
    messagingSenderId: '123456789012',
    projectId: 'nimbus-ai-project',
    databaseURL: 'https://nimbus-ai-project.firebaseio.com',
  );

  /// iOS Firebase configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLqLjzLc3jH1e5kJ9pG8tM2nB7cD4fH5i',
    appId: '1:123456789012:ios:xyz789uvw456xyz789uvw',
    messagingSenderId: '123456789012',
    projectId: 'nimbus-ai-project',
    databaseURL: 'https://nimbus-ai-project.firebaseio.com',
    iosBundleId: 'com.example.nimbusai',
  );

  /// Windows Firebase configuration
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLqLjzLc3jH1e5kJ9pG8tM2nB7cD4fH5i',
    appId: '1:123456789012:windows:pqr123stu890pqr123stu',
    messagingSenderId: '123456789012',
    projectId: 'nimbus-ai-project',
    databaseURL: 'https://nimbus-ai-project.firebaseio.com',
  );
}
