# -*- coding: utf-8 -*-
"""Logistic_Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Oba9RP0DIvIMCH0ABK0jtYGZZc7CW7qc
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("/content/Updated_Merged_Data.csv")
df.head()

df.info()

print(df.isnull().sum())

(df == 0).sum()

cols = [
    "temperature_C",
    "humidity_%"
]

for col in cols:
    df[col] = df[col].replace(0, np.nan)
    df[col] = df[col].fillna(df[col].mean())

(df == 0).sum()

df = df[
    (df["satellite_elevation_deg"] >= 10) &
    (df["satellite_elevation_deg"] <= 70) &
    (df["satellite_azimuth_deg"] >= 0) &
    (df["satellite_azimuth_deg"] <= 360) &
    (df["satellite_prn"] >= 1) &
    (df["satellite_prn"] <= 32)
]

print("Filtered dataset size:", df.shape)

features = [
    "temperature_C",
    "humidity_%",
    "snr_measured_dbhz",
    "rain_sensor_value"
]

X = df[features]
y = df["label"]

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

model = LogisticRegression(
    multi_class="multinomial",
    solver="lbfgs",
    max_iter=1000
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

print(classification_report(y_test, y_pred))

print(confusion_matrix(y_test, y_pred))

print("Model Coefficients:")
print(model.coef_)

print("Intercept:")
print(model.intercept_)

np.save("weights.npy", model.coef_)
np.save("bias.npy", model.intercept_)

print("Feature Min:", scaler.data_min_)
print("Feature Max:", scaler.data_max_)